version: 2.1
jobs:
  build:
    docker:
      - image: pletessier/taranis:unstable
    steps:
      - checkout
      - run:
          working_directory: src/python/models/
          command: python setup.py sdist bdist_wheel
      - run:
          working_directory: src/python/models/
          command: python -m twine upload --username $pypi_username --password $pypi_password dist/*