version: 2.1
jobs:
  build:
    docker:
      - image: pletessier/taranis:0.1.0
    steps:
      - checkout
      - run:  cd src/python/models/
      - run:  python setup.py sdist bdist_wheel
      - run:  python -m twine upload --username $pypi_username --password $pypi_password dist/*